CO2RefrigeratorCloud/urls.py
from django.conf.urls import patterns, url, include

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),

    # Login
    url(r'', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),

    # Management
    url(r'^$', 'cloud.views.index', name="index"),
    url(r'^dashboard/$', 'cloud.views.dashboard'),
    url(r'^register/$', 'cloud.views.register'),
    url(r'^device/(?P<p_device_id>\w+)$', 'cloud.views.device'),
    # url(r'^device/(?P<p_device_id>\w+)$/log/$', 'cloud.views.showlog'),

    # API of Devices
    url(r'^api/log/$', 'cloud.views.api_log'),
    url(r'^api/request/$', 'cloud.views.api_request'),
    url(r'^api/device/$', 'cloud.views.api_device'),

)

cloud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django import forms

# class User(AbstractBaseUser):
#     username = models.CharField(max_length=40, unique=True)
#
#     USERNAME_FIELD = 'username'
#
#     def __unicode__(self):
#         return u'%s' % (self.get_username())

class Device(models.Model):
    device_id = models.CharField(max_length=50, primary_key=True)
    user = models.ForeignKey(User, null=True, blank=True)

    def __unicode__(self):
        return u'%s' % (self.device_id)

class DeviceForm(forms.Form):
    device_id = forms.CharField(max_length=50)
    user = forms.CharField()

class DeviceAdmin(admin.ModelAdmin):
    list_display = ('device_id', 'user')

class Status(models.Model):
    device_id = models.OneToOneField(Device)
    power = models.NullBooleanField(default=True, null=True)
    co2 = models.FloatField(null=True)
    o2 = models.FloatField(null=True)
    temperature = models.FloatField(null=True)
    humidity = models.FloatField(null=True)

    def __unicode__(self):
        return u'%s' % (self.device_id)

class StatusAdmin(admin.ModelAdmin):
    list_display = ('device_id', 'co2', 'o2', 'temperature', 'humidity', 'power')

class Log(models.Model):
    device_id = models.ForeignKey(Device)
    log = models.TextField(blank=False, null=False)
    log_time = models.DateTimeField(auto_now=True, null=True)

    def __unicode__(self):
        return u'%s, %s' % (self.device_id, self.log)

class LogAdmin(admin.ModelAdmin):
    list_display = ('device_id', 'log', 'log_time')

class Request(models.Model):
    device_id = models.ForeignKey(Device)
    request = models.CharField(max_length=30)
    value = models.FloatField()
    req_time = models.DateTimeField(auto_now=True, null=True)
    isSended = models.BooleanField(default=False)

    def __unicode__(self):
        return u'%s, %s' % (self.device_id, self.request)

class RequestAdmin(admin.ModelAdmin):
    list_display = ('device_id', 'request', 'value', 'req_time', 'isSended')

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CO2 Incubator Cloud Management{% endblock %}</title>
    {% if not user.is_authenticated %}
    <script>location.href="{% url 'index' %}";</script>
    {% endif %}

    <!-- Core CSS - Include with every page -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/sb-admin.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}font-awesome/css/font-awesome.css" rel="stylesheet">
</head>
<body>
    <div id="wrapper">
    {% block navigation %}
      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">CO<sub>2</sub> Incubator Cloud Manager</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="/register"><i class="fa fa-edit"></i> Register</a></li>
            {% include "device_nav.html" %}
          </ul>

          <ul class="nav navbar-nav navbar-right navbar-user">
            <li class="dropdown user-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ user }} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                {#<li><a href="#"><i class="fa fa-user"></i> Profile</a></li>#}
                <li><a href="{% url 'auth_password_change' %}"><i class="fa fa-gear"></i> Change password</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'auth_logout' %}"><i class="fa fa-power-off"></i> Log Out</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
    {% endblock %}

    {% block content %}{% endblock %}

    </div>
    <!-- /#wrapper -->

    <!-- Core Scripts - Include with every page -->
    <script src="{{ STATIC_URL }}js/jquery-1.10.2.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- SB Admin Scripts - Include with every page -->
    <script src="{{ STATIC_URL }}js/sb-admin.js"></script>

    <!-- Page Specific Plugins -->
    {% block plugin %}{% endblock %}
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    {% load device_tag %}
    <div id="page-wrapper">

        <div class="row">
            <div class="col-lg-12">
                <h1>Dashboard <small>Overview</small></h1>
                <ol class="breadcrumb">
                    <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
                </ol>
                {% include 'message.html' %}

                <div class="row">
                  <div class="col-lg-12">
                    <h2>Average Status</h2>
                  </div>
                  <div class="col-lg-12">
                  </div>
                  <div class="col-lg-3">
                    <div class="panel panel-info">
                      <div class="panel-heading">
                        <div class="row">
                          <div class="col-xs-6">
                            <i class="fa fa-flask fa-5x"></i>
                          </div>
                          <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{{ user|get_avg_co2|floatformat:1 }}%</p>
                            <p class="announcement-text">CO<sub>2</sub></p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="panel panel-warning">
                      <div class="panel-heading">
                        <div class="row">
                          <div class="col-xs-6">
                            <i class="fa fa-asterisk fa-5x"></i>
                          </div>
                          <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{{ user|get_avg_o2|floatformat:1 }}%</p>
                            <p class="announcement-text">O<sub>2</sub></p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="panel panel-danger">
                      <div class="panel-heading">
                        <div class="row">
                          <div class="col-xs-6">
                            <i class="fa fa-sun-o fa-5x"></i>
                          </div>
                          <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{{ user|get_avg_temperature|floatformat:1 }}&deg;c</p>
                            <p class="announcement-text">Temperature</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="panel panel-success">
                      <div class="panel-heading">
                        <div class="row">
                          <div class="col-xs-6">
                            <i class="fa fa-tint fa-5x"></i>
                          </div>
                          <div class="col-xs-6 text-right">
                            <p class="announcement-heading">{{ user|get_avg_humidity|floatformat:1 }}%</p>
                            <p class="announcement-text">Humidity</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /.row -->

                {% if user|is_display_devices_menu %}
                <div class="row">
                    <div class="col-lg-12">
                        <h2>My Devices</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                <tr>
                                    <th class="header col-lg-2">Device ID </th>
                                    <th class="header col-lg-2">CO<sub>2</sub> </th>
                                    <th class="header col-lg-2">O<sub>2</sub> </th>
                                    <th class="header col-lg-2">Temperature </th>
                                    <th class="header col-lg-2">Humidity </th>
                                    <th class="header col-lg-2">Power </th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in user|get_my_devices_and_status %}
                                <tr>
                                    <td>{{ item.status.device_id }}</td>
                                    <td>{{ item.status.co2|floatformat:1 }}%</td>
                                    <td>{{ item.status.o2|floatformat:1 }}%</td>
                                    <td>{{ item.status.temperature|floatformat:1 }}&deg;c</td>
                                    <td>{{ item.status.humidity|floatformat:1 }}%</td>
                                    <td>
                                        {% if item.status.power == True %}
                                        <span class="label label-success">ON</span>
                                        {% elif item.status.power == False %}
                                        <span class="label label-danger">OFF</span>
                                        {% else %}
                                        <span class="label label-warning">Unknown</span>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="2">Sorry, no log data of this device.</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
                {% endif %}

                <div class="row">
                  <div class="col-lg-12">
                    <div class="panel panel-primary">
                      <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Traffic Statistics</h3>
                      </div>
                      <div class="panel-body">
                        <div id="morris-chart-area"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /.row -->

                <div class="row">
                  <div class="col-lg-12">
                    <div class="panel panel-primary">
                      <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-clock-o"></i> Recent Activity</h3>
                      </div>
                      <div class="panel-body">
                        <div class="list-group">
                          <a href="#" class="list-group-item">
                            <span class="badge">just now</span>
                            <i class="fa fa-check"></i> Completed task: "asdf1234 was registered"
                          </a>
                          <a href="#" class="list-group-item">
                            <span class="badge">2 hours ago</span>
                            <i class="fa fa-check"></i> Completed task: "zxcv1234 was registered"
                          </a>
                          <a href="#" class="list-group-item">
                            <span class="badge">two days ago</span>
                            <i class="fa fa-calendar"></i> Created account
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

    </div><!-- /#page-wrapper -->
{% endblock %}

{% block plugin %}
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>
    <script src="{{ STATIC_URL }}js/morris/chart-data-morris.js"></script>
    <script src="{{ STATIC_URL }}js/tablesorter/jquery.tablesorter.js"></script>
    <script src="{{ STATIC_URL }}js/tablesorter/tables.js"></script>
{% endblock %}

templates/device_nav.html
{% load device_tag %}
{% block devices %}
    {% if user|is_display_devices_menu %}
            <li class="dropdown open">
              <a href="#" class="dropdown-toggle"><i class="fa fa-caret-square-o-down"></i> My Devices <b class="caret"></b></a>
              <ul class="dropdown-menu">
              {% for device in user|get_my_devices %}
                <li><a href="/device/{{ device.device_id }}"><i class="fa fa-hdd-o"></i> {{ device.device_id }}</a></li>
              {% endfor %}
              </ul>
            </li>
    {% endif %}
{% endblock %}

templates/message.html
{% block message %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ message|safe }}
    </div>
{% endfor %}
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div id="page-wrapper">

        <div class="row">
            <div class="col-lg-12">
                <h1>Register <small>register your device into cloud server</small></h1>
                <ol class="breadcrumb">
                    <li class="active"><i class="fa fa-edit"></i> Register</li>
                </ol>
                {% include 'message.html' %}
                <div class="row">
                    <div class="col-lg-12">
                        <form role="form" action="." method="POST">
                            {% csrf_token %}
                            <input id="id_user" name="user" type="hidden" value="{{ user }}"/>
                            <div class="form-group">
                                <label>Device id</label>
                                <input class="form-control" placeholder="Enter the device ID what you have" id="id_device_id" maxlength="50" name="device_id" type="text">
                            </div>
                            <button type="submit" class="btn btn-default">{% trans "Register" %}</button>
                            <button type="reset" class="btn btn-default">{% trans "Reset Button" %}</button>
                        </form>
                    </div>
                </div>
    </div><!-- /#page-wrapper -->
{% endblock %}

templates/registration_base.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CO2 Incubator Cloud Management{% endblock %}</title>

    <!-- Core CSS - Include with every page -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- SB Admin CSS - Include with every page -->
    <link href="{{ STATIC_URL }}css/sb-admin.css" rel="stylesheet">
</head>
<body>
    {% block content %}{% endblock %}

    <!-- Core Scripts - Include with every page -->
    <script src="{{ STATIC_URL }}js/jquery-1.10.2.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- SB Admin Scripts - Include with every page -->
    <script src="{{ STATIC_URL }}js/sb-admin.js"></script>

    <!-- Page Specific Plugins -->
    {% block plugin %}{% endblock %}
</body>
</html>